### ISSUE TITLE
Deadlock in HTTP Adapter of Hono 0.6-Final 

### ISSUE THREAD

**Issue by Christian-Schmid** [eclipse/hono#696] opened 2018-07-06 14:59 UTC
Hi Hono Devs,

we're running Hono 0.6 (Release) in a kubernetes cluster.
Sometimes we are encountering problems with an unresponsive Hono HTTP Adapter. 

The last time we took a thread dump of the pod, which shows a java deadlock:

```
Found one Java-level deadlock:
=============================
"vert.x-eventloop-thread-4":
  waiting to lock monitor 0x00007fc1c000d0a8 (object 0x00000000f07a7c40, a io.vertx.ext.web.impl.RouteImpl),
  which is held by "vert.x-eventloop-thread-0"
"vert.x-eventloop-thread-0":
  waiting to lock monitor 0x00007fc1c408c318 (object 0x00000000f07a8fc0, a io.vertx.ext.web.impl.RouteImpl),
  which is held by "vert.x-eventloop-thread-4"
```
I'm attaching the log file and thread dump:
[logs-from-hono-adapter-http-vertx-in-hono-adapter-http-vertx.txt](https://github.com/eclipse/hono/files/2170657/logs-from-hono-adapter-http-vertx-in-hono-adapter-http-vertx.txt)
[threadDump.log](https://github.com/eclipse/hono/files/2170659/threadDump.log)
 
Sadly I don't have concrete steps to reproduce the issue yet. But maybe someone else experienced  something similar or got a hunch what could be the problem.

**Comment by sophokles73** [comment] 2018-07-09 17:01
I have started to look into this. I am quite sure what the problem is (thanks to the thread dump) but I am not (yet) sure how to properly address the problem.

**Comment by sophokles73** [comment] 2018-07-10 11:47
The problem seems to be that we *switch* the vert.x `Context` while processing requests. When a request comes in it is handled on the event loop context that has been created when the HTTP adapter verticle gets deployed. This Context is associated with one of the event loop threads, say *event-loop-thread-0*.

When Spring instantiates the HonoClient instances for connecting to the registry and AMQP network, these instances all create a new vert.x Context to run on in their constructor. So, let's say the client for accessing the Tenant service runs on a Context that is associated with *event-loop-thread-1*.

Now, when an HTTP request is being processed, we first try to authenticate the device which includes a lookup of the tenant that the device belongs to. Thus, the request handler invokes the Tenant HonoClient which will add a task to the *event-loop-thread-1*'s event loop. When the result of the lookup operation is received from the Tenant service (still on *event-loop-thread-1*) the HonoClient completes the result future and the processing of the HTTP request can continue. This involves invocation of `Router.next()` in order to determine the next handler to invoke for processing the HTTP request. However, the Router instance (which has been created on *event-loop-thread-0* when the HTTP server has been started), will now be concurrently accessed from two threads: *event-loop-thread-1* (with the result of the tenant lookup) as well as from *event-loop-thread-0* (for handling the next request coming in from a device).

We now have a situation where two threads try to lock on the same objects (the `Route`s registered in the Router) which seems to be prone to ending in the observed deadlock situation.

I think that we will need to make sure that the result of the operations invoked on the HonoClient instances gets processed on the calling code's Context (and underlying thread). I am currently thinking about ways how to achieve this.

**Comment by sophokles73** [comment] 2018-07-12 08:07
As a corollary to the strategy of fixing this issue, we also need to get the validation of client certificates off of the event loop because the `TenantApiBasedX509TrustManager` uses the `HonoClient` for the Tenant service to look up the tenant that the device belongs to. However, since the `X509TrustManager.checkClientTrusted` method is blocking the current thread, we cannot run both on the same event loop (we would never get the result of the tenant lookup because the result handler is scheduled to the same event loop which is still blocked by the trust manager check).

Assuming that we still want to do validation of client certs based on the dynamic lookup of the trust anchor, we will need to move the validation of the certificate chain up to the application level, i.e. into the `X509AuthHandler`. This actually is less frightening as it at first seems because we need to lookup the tenant there anyway in order to be able to do the credentials lookup (which is always scoped to the tenant).

**Comment by sophokles73** [comment] 2018-07-19 09:54
fixed in https://github.com/eclipse/hono/commit/4e7dc3aeba95d03804518aed3655ab2c71f82a2c

**Closed by sophokles73** 2018-07-19 09:54 UTC
Labels: HTTP Adapter, bug
