### ISSUE TITLE
AMQP adapter error codes for resource limits exceeded

### ISSUE THREAD

**Issue by bordeuax** [eclipse/hono#1846] opened 2020-03-20 09:31 UTC
In case of  resource limits exceeded  we have different errors codes; 
For example :
* message limits error code is 429 `HttpResponseStatus.TOO_MANY_REQUESTS` 
* connection limits  error code is 403 `HttpResponseStatus.HTTP_FORBIDDEN`
* connection duration limits  error code is 403 `HttpResponseStatus.HTTP_FORBIDDEN` 

What was the reason behind to have different code instead to have one code like `HttpResponseStatus.TOO_MANY_REQUESTS` as common error code when limits are exceeded ?

**Comment by sophokles73** [comment] 2020-03-20 09:33
@kaniyan would you mind explaining?

**Comment by kaniyan** [comment] 2020-03-20 13:39
Connection limit is only supported by  _MQTT_ and _AMQP_ protocol adapters which maintain connection state. In case of MQTT, when a connect request is being declined, as per the spec there are five possible status codes that can be sent back and after discussion on that PR, it has been agreed to use `CONNECTION_REFUSED_NOT_AUTHORIZED`. There is no staus code that corresponds to `TOO_MANY_REQUESTS`. To make it sync with that of MQTT, in case of AMQP, it has been mapped to `UNAUTHORIZED_ACCESS`. There was already a mapping between http codes and _AMQP_ error conditions, in order to get the above _AMQP_ error condition a http status code of `HTTP_FORBIDDEN` has been chosen.

**Comment by bordeuax** [comment] 2020-03-21 14:25
@kaniyan , thanks for your detailed feedback. I am referring only to AMQP protocol and with possibility to map exactly the same error code and error condition to other protocols ( yes, of course, if it's supported by protocol). My main point here is usability and customer experience, more we have precise and  self-explained errors or error conditions less we need support effort.  
Why not to adopt Hono's very precise and self-explained errors and errors conditions something like :  
   *  `hono:message-data-limit-exceeded`
   *  `hono:parallel-connections-limit-exceeded`
   * `hono:total-connection-time-limit-exceeded`

**Comment by sophokles73** [comment] 2020-04-01 10:12
@bordeuax The AMQP adapter currently checks the connection limit(s) as part of the SASL handshake with the client. Thus, if any of the limits is exceeded, we currently fail the SASL handshake. However, AMQP only provides for a limited set of *outcome codes* that are conveyed to the client. There is no way to provide additional information as to why authentication failed.
So, in order to provide a more meaningful error message, we would need to change the `AmqpAdapterSaslAuthenticatorFactory` to succeed the SASL handshake whenever the credentials are ok and then perform the limits check as part of handling the client's AMQP *open* frame instead. We could then close the AMQP connection providing a more meaningful error description.

@kaniyan WDYT?

**Comment by kaniyan** [comment] 2020-04-01 10:24
> @bordeuax The AMQP adapter currently checks the connection limit(s) as part of the SASL handshake with the client. Thus, if any of the limits is exceeded, we currently fail the SASL handshake. However, AMQP only provides for a limited set of _outcome codes_ that are conveyed to the client. There is no way to provide additional information as to why authentication failed.
> So, in order to provide a more meaningful error message, we would need to change the `AmqpAdapterSaslAuthenticatorFactory` to succeed the SASL handshake whenever the credentials are ok and then perform the limits check as part of handling the client's AMQP _open_ frame instead. We could then close the AMQP connection providing a more meaningful error description.
> 
> @kaniyan WDYT?

@sophokles73 There is also another issue #1848 reporting the same. The _AMQP_ adapter responds with  error code corresponding to the authentication failure even though the connection limit is exceeded or adapter is disabled. One of my [suggestion](https://github.com/eclipse/hono/issues/1848#issuecomment-601743651) on that issue was to move limit checks (tenant and adapter level) and adapter enabled or not check outside the `AmqpAdapterSaslAuthenticatorFactory`. :+1:  from my side.

**Comment by sophokles73** [comment] 2020-04-01 11:40
duplicate of #1848

**Closed by sophokles73** 2020-04-01 11:40 UTC
Labels: AMQP Adapter, Metrics, question
