### ISSUE TITLE
Hono consume from many application

### ISSUE THREAD

**Issue by mhumoglu** [eclipse/hono#685] opened 2018-07-03 08:03 UTC
Hi ,
I want to  hono consume from many application. But only i consumed from one application.when i consume from many applications, applications are consuming one by one. (first message access first application, it not access second application  and  second message access second application, it not access first application)

Regards

**Comment by sophokles73** [comment] 2018-07-03 08:22
Not sure if I understand your question correctly. Are you referring to not being able to consume the same message in multiple applications?

**Comment by mhumoglu** [comment] 2018-07-03 08:39
No i can not sending the same message to multiple applications at the same time.

**Comment by sophokles73** [comment] 2018-07-03 08:46
That is by design. The Dispatch Router by default uses *balanced* delivery mode for messages, i.e. when you connect multiple applications which try to consume messages using the same source address, then the router will send the messages to any of the consumers for which it has credit available.

You can set the delivery mode to *multicast* as well (refer to the Dispatch Router documentation for how to do that). However, keep in mind that overall throughput of messages will be determined by the slowest consumer/application in this setup. That is why we actually discourage this configuration and instead advise to use something like Apache Kafka in order to buffer messages for consumption by multiple consumers.

**Comment by sophokles73** [comment] 2018-07-03 13:38
@mhumoglu can we close this issue?

**Closed** 2018-07-19 07:33 UTC
Labels: question
