### ISSUE TITLE
Auth & device registry keep getting OOMKilled with default limits

### ISSUE THREAD

**Issue by ghys** [eclipse/hono#817] opened 2018-09-08 11:10 UTC
I'm running Hono 0.7 on Kubernetes using the deployment script with next to no changes to the resources, i.e. I haven't changed anything as described in https://www.eclipse.org/hono/deployment/resource-limitation/.

`kubectl describe node` extract:
```
Allocatable:
 cpu:                2
 ephemeral-storage:  63941352Ki
 hugepages-2Mi:      0
 memory:             7661808Ki
 pods:               110
System Info:
 Machine ID:                 996ebefb2cc44da1ae864d3c078ca1eb
 System UUID:                EC265B0A-9CA8-1B71-3E38-9FB5BC8E14FF
 Boot ID:                    9f7d86b5-42ca-44cf-a8aa-1f6c9b9494d9
 Kernel Version:             4.4.0-1066-aws
 OS Image:                   Ubuntu 16.04.2 LTS
 Operating System:           linux
 Architecture:               amd64
 Container Runtime Version:  docker://17.3.2
 Kubelet Version:            v1.11.2
 Kube-Proxy Version:         v1.11.2
Non-terminated Pods:         (20 in total)
  Namespace                  Name                                               CPU Requests  CPU Limits  Memory Requests  Memory Limits
  ---------                  ----                                               ------------  ----------  ---------------  -------------
...
  hono                       hono-service-auth-7949d57744-4ch5t                 0 (0%)        0 (0%)      196Mi (2%)       196Mi (2%)
  hono                       hono-service-device-registry-85d87b66dd-m8nsl      0 (0%)        0 (0%)      256Mi (3%)       256Mi (3%)
...
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource  Requests          Limits
  --------  --------          ------
  cpu       778m (38%)        498m (24%)
  memory    3582622656 (45%)  3768528Ki (49%)
```

However I'm noticing that two services, the auth service and the device registry, are regularly OOMKilled (every few hours):
```
$ kubectl -n hono get pod
NAME                                            READY     STATUS    RESTARTS   AGE
grafana-5645865df8-4prlg                        1/1       Running   5          14d
hono-adapter-http-vertx-7d78bc5f4d-pwmgd        1/1       Running   6          14d
hono-adapter-mqtt-vertx-799bd5858c-stw6b        1/1       Running   3          5d
hono-artemis-797c695777-gljgv                   1/1       Running   5          14d
hono-dispatch-router-5fd7756dfb-bmnzf           1/1       Running   5          14d
hono-service-auth-7949d57744-4ch5t              1/1       Running   172        11d
hono-service-device-registry-85d87b66dd-m8nsl   1/1       Running   79         14d
influxdb-784f8f677c-xd6k5                       1/1       Running   5          14d
```
Here's the relevant `describe pod` output for the auth service (the device registry is similar):
```
$ kubectl -n hono describe pod -l app=hono-service-auth
...
    Last State:     Terminated
      Reason:       OOMKilled
...
    Restart Count:  172
    Limits:
      memory:  196Mi
    Requests:
      memory:   196Mi
```
To confirm `-Xmx150m` is set:
```
$ kubectl -n hono describe deployment -l app=hono-service-auth
...
    Environment:
      SPRING_CONFIG_LOCATION:  file:///etc/hono/
      SPRING_PROFILES_ACTIVE:  authentication-impl,dev
      LOGGING_CONFIG:          classpath:logback-spring.xml
      _JAVA_OPTIONS:           -Xmx150m
      KUBERNETES_NAMESPACE:     (v1:metadata.namespace)
```
I can increase the limits but wanted to know whether it's just me or are the defaults wrong? What could be the cause of these memory issues?
Thanks!

**Comment by sysexcontrol** [comment] 2018-09-10 11:51
Hi @ghys , thanks for reporting.

I can confirm that you seem to be sticking to Hono's defaults regarding memory limits in the kubernetes deplyoment scripts, so I made some closer investigations regarding the memory consumption of both `device registry` and `auth server`.
So far without success to find anything:
- local docker swarm limits did not show any out of memory behaviour (`docker stats` looks healthy)
- profiling the `device registry` and `auth server` did not show any memory leak
- all done while sending a lot of telemetry data downstream to an application

So, could you provide please
- are you sending telemetry data/event data/command and control to your kubernetes before you encounter OOM errors after some hours? Or is it happening without doing `anything`?
- which version of Hono exactly do you use? 0.7 release docker images? Self built from source? 
- can you provide logs of the device registry and auth server showing the OOM?


Regarding increasing the limits: yes, this could be a good idea of course if you have a lot of devices registered e.g. and the limits are becoming just too narrow. So, increase them to e.g. 384Mi instead of 256Mi and try to see if everything is stable then would help as an information as well.
If a memory leak should be responsible this wouldn't help for very long before OOM occurs again.

Waiting for your answer!

**Comment by ghys** [comment] 2018-09-10 12:39
Thanks for investigating!

> are you sending telemetry data/event data/command and control to your kubernetes before you encounter OOM errors after some hours? Or is it happening without doing anything?

It's not a production environment yet, but I'm still having devices sending 2-3 telemetry messages per minute overall, and the occasional event and command & control too. I haven't checked if it's stable without activity.

> which version of Hono exactly do you use? 0.7 release docker images?

Yes, I simply used the `kubernetes_deploy.sh` script in https://www.eclipse.org/downloads/download.php?file=/hono/eclipse-hono-deploy-0.7.tar.gz.

> can you provide logs of the device registry and auth server showing the OOM?

Unfortunately they seem to be killed by Kubernetes so there's nothing in the logs (that I know of), they simply stop and restart.

I can also confirm increasing the limits of both services seems to work, after I increased them to 512Mi 2 days ago the pods there haven't been any restart so far (it would certainly have been the case before):
```
s$ kubectl get pod -n hono
NAME                                            READY     STATUS    RESTARTS   AGE
...
hono-service-auth-6586b59948-6p6qh              1/1       Running   0          2d
hono-service-device-registry-848fdfccbd-28l4r   1/1       Running   0          2d
```
Here is the current memory situation:
```
$ kubectl top pod -n hono
NAME                                            CPU(cores)   MEMORY(bytes)
...
hono-service-auth-6586b59948-6p6qh              0m           233Mi
hono-service-device-registry-848fdfccbd-28l4r   0m           280Mi
```
As you can see they stand well above the 192Mi/256Mi set as previous limits, which explains why they were getting killed. I will monitor the evolution of those metrics.

Hope this helps!

**Comment by ghys** [comment] 2018-09-10 13:03
Here are some interesting graphs from 2 weeks ago:
![image](https://user-images.githubusercontent.com/2004147/45298799-dbb1dd00-b509-11e8-9963-5622aefbdde3.png)
![image](https://user-images.githubusercontent.com/2004147/45298875-1ddb1e80-b50a-11e8-9a8c-cad5ae3fb781.png)
![image](https://user-images.githubusercontent.com/2004147/45298917-3c411a00-b50a-11e8-9470-7de2b8bb150e.png)

It was very near the limit most of the time. Maybe they are just too low? According to https://www.eclipse.org/hono/deployment/resource-limitation/:

> -Xmx can be used to explicitly set the maximum amount of memory used for the heap. As a rule of thumb, setting this value to 60-70% of the container’s (limited) amount of memory should usually work. Based on the application’s memory usage characteristics, increasing the value to 80 or even 90% might also work.

**Comment by sysexcontrol** [comment] 2018-09-10 13:10
@ghys thanks for providing this - I have the suspicion as well that the limits are set quite narrow.
I have seen something similiar in docker swarm - but it never failed so far.

Nevertheless, I would increase the limits, but would rather like to stick closer to the current limit than you did in your successful changes two days ago.
So, increase them rather to `Xmx=384Mi" instead of `512Mi`.

Would you mind trying this out in your environment for 2 more days to see if the limit of `384Mi` would fix the problem for you as well?
Asking since Hono is made for managing large amounts of devices, so being scaled up is a fundamental issue. And then the limits matter a lot for the complete memory consumption.

Thanks for your support, if possible!

**Comment by ghys** [comment] 2018-09-10 15:11
I can't alter the deployments today but will try when I get the chance.
I haven't increased the `Xmx` Java option (set respectively to `150Mi` and `180Mi` for the auth and registry services), only the resource limit (https://kubernetes.io/docs/tasks/configure-pod-container/assign-memory-resource/#specify-a-memory-request-and-a-memory-limit). Maybe it could be an option to keep them as they were and decrease `Xmx` instead.

So far since I deployed the memory usage has been relatively stable, above the old limits (drawn on these graphs for reference) but not too much:
![image](https://user-images.githubusercontent.com/2004147/45305978-c645ae80-b51b-11e8-82ea-37b84965d848.png)
![image](https://user-images.githubusercontent.com/2004147/45306116-22103780-b51c-11e8-8d34-7945a166801c.png)

I think we'd be good with only adding 64Mi, i.e. `256Mi` for the auth and `320Mi` for the registry, will confirm.

**Comment by sysexcontrol** [comment] 2018-09-10 16:05
:+1: experiments in your environment appreciated!

I guess you meant `it could be an option to keep Xmx as it was and increase the kubernetes limits, e.g. from 256Mi to 320Mi for the device registry` (and similar for the auth service), right?
This would make a lot of sense to me, and we would stick to try to keep memory requirements as low as possible.

Looking forward to your results, tell me if you want to provide a pull request or prefer to let me do the changes then...

**Comment by ghys** [comment] 2018-09-10 16:55
> t could be an option to keep Xmx as it was and increase the kubernetes limits, e.g. from 256Mi to 320Mi for the device registry

No, that's what I did, but I wondered if keeping the kubernetes limits as 192Mio and 256Mio but decreasing the Java maximum heap size to for example resp. `-Xmx96m` and `-Xmx128m` (from resp. `-Xmx150m` and `-Xmx180m` currently) could also do the trick. It's probably more dangerous though because it could lead to Java OutOfMemoryExceptions...

I'm interested to know if Hono can run reliably (only the bare minimum, MQTT/HTTP adapters, auth, registry, dispatch router and Artemis) on a smaller host with only 4 GB of RAM.

**Comment by sysexcontrol** [comment] 2018-09-11 13:30
I completely see your point, sounds reasonable.

As a quick information : I configured the `-Xmx80m` for the device registry locally (not running in a container) and monitored the heap usage and the log while firing telemetry messages to the HTTP adapter. No problems, a clean sawtooth behaviour, no OOM exceptions, no malfunctions.

So go ahead and tweak Xmx down and let's see if it works in your environment as well. Then we can lower the Xmx settings in the default descriptors of Hono, too (but being careful, setting them too low may cause too many problems, and it is hard to find out what is `too low`).
To me it looks like your original problem came from the small amount of memory that was left for the pod after the JVM took it's full memory assignment. And this would be exactly addressed by what you proposed: leave the kubernetes limits as they were and lower the Xmx.

If you tried it out, please post your results here, thanks!

**Comment by ghys** [comment] 2018-09-21 07:06
FYI: Here are some memory usage graphs after about 2 weeks of running untouched with `-Xmx150m` /`-Xmx180m` and ample limits:
```
  eclipse-hono-service-auth:
    Image:          eclipse/hono-service-auth:0.7
    State:          Running
      Started:      Fri, 21 Sep 2018 03:51:38 +0000
    Last State:     Terminated
      Reason:       Error
      Exit Code:    137
      Started:      Wed, 19 Sep 2018 20:32:08 +0000
      Finished:     Fri, 21 Sep 2018 03:50:52 +0000
    Ready:          True
    Restart Count:  6
    Limits:
      memory:  512Mi
    Requests:
      memory:   512Mi
    Environment:
      _JAVA_OPTIONS:           -Xmx150m
```
![image](https://user-images.githubusercontent.com/2004147/45865210-02c7a480-bd7d-11e8-9f14-a1cdd3214fad.png)

```
  eclipse-hono-service-device-registry:
    Image:          eclipse/hono-service-device-registry:0.7
    State:          Running
      Started:      Fri, 21 Sep 2018 03:51:38 +0000
    Last State:     Terminated
      Reason:       Error
      Exit Code:    137
      Started:      Wed, 19 Sep 2018 20:31:54 +0000
      Finished:     Fri, 21 Sep 2018 03:50:52 +0000
    Ready:          True
    Restart Count:  6
    Limits:
      memory:  512Mi
    Requests:
      memory:   512Mi
    Environment:
      _JAVA_OPTIONS:           -Xmx180m
```
![image](https://user-images.githubusercontent.com/2004147/45865183-ef1c3e00-bd7c-11e8-9e55-385a71dcf0c8.png)

Both container restarted only 6 times in the period, seemingly always together but this time because of errors (I haven't investigated those).
I'll try again with lower heap sizes.

**Comment by sophokles73** [comment] 2018-09-24 09:05
> I'm interested to know if Hono can run reliably (only the bare minimum, MQTT/HTTP adapters, auth, registry, dispatch router and Artemis) on a smaller host with only 4 GB of RAM.

This is what we do on the Sandbox which, in fact, has only 3.75GB of RAM ... However, there we deploy to Docker Swarm, i.e. we are not running Kubernetes on the Sandbox in order to not waste too much memory on infrastructure.

**Comment by sophokles73** [comment] 2019-03-25 09:45
@ghys is this still an issue? If not, can you close this issue?

**Closed** 2019-04-02 14:57 UTC
Labels: question
