### ISSUE TITLE
HonoClient: handle a failed "attach" when creating Consumers/Receivers

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#459] opened 2018-01-23 10:27 UTC
When using the `createEventConsumer()` or `createTelementryConsumer()`methods on a `HonoClient`, the given `creationHandler` param should fail if the "attach" on the link fails (i.e. "detach" was received).

**Comment by pellmann** [comment] 2018-01-24 10:54
Should be fixed with https://github.com/eclipse/hono/commit/f4a667aab814e51988d87af2712d6c1faa112871. Could you check?

**Comment by calohmn** [comment] 2018-01-29 13:52
LGTM. I see the missing handling of `detach(close=false)` is part of a different ticket now (#467).

**Comment by sophokles73** [comment] 2018-02-08 14:08
@calohmn can you verify and close this issue if the problem is fixed from your point of view?

**Closed** 2018-02-19 10:53 UTC
Labels: Client, bug
