### ISSUE TITLE
Exception in readinessCheck handling

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#361] opened 2017-10-06 14:39 UTC
Running the device registry in a kubernetes cluster, we noticed the following exception:

```
14:04:22.788 [vert.x-eventloop-thread-3] DEBUG o.e.h.s.a.d.DelegatingAuthenticationService - checking connection to Authentication service
14:04:22.790 [vert.x-eventloop-thread-3] DEBUG o.e.h.s.a.d.AuthenticationServerClientConfigProperties - using certificates from file [/run/secrets/trusted-certs.pem] as trust anchor
14:04:22.791 [vert.x-eventloop-thread-3] DEBUG o.e.h.s.a.d.AuthenticationServerClientConfigProperties - using key [/run/secrets/device-registry-key.pem] and certificate [/run/secrets/device-registry-cert.pem] for identity
14:04:22.793 [vert.x-eventloop-thread-3] DEBUG o.e.h.c.ConnectionFactoryImpl - connecting to AMQP 1.0 container [amqps://hono-service-auth.hono:5671]
14:04:24.175 [vert.x-eventloop-thread-3] DEBUG o.e.h.c.ConnectionFactoryImpl - connected to AMQP 1.0 container [amqps://hono-service-auth.hono:5671], opening connection ...
14:04:24.239 [vert.x-eventloop-thread-3] DEBUG o.e.h.c.ConnectionFactoryImpl - connection to container [Hono-Auth-0.0.0.0:5671] at [amqps://hono-service-auth.hono:5671] open
14:04:24.270 [vert.x-eventloop-thread-3] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.IllegalStateException: Result is already complete: failed
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:107)
	at org.eclipse.hono.service.auth.delegating.DelegatingAuthenticationService.lambda$null$0(DelegatingAuthenticationService.java:87)
	at org.eclipse.hono.connection.ConnectionFactoryImpl.lambda$handleConnectionAttemptResult$1(ConnectionFactoryImpl.java:149)
	at io.vertx.proton.impl.ProtonConnectionImpl.fireRemoteOpen(ProtonConnectionImpl.java:357)
	at io.vertx.proton.impl.ProtonTransport.handleSocketBuffer(ProtonTransport.java:105)
	at io.vertx.core.net.impl.NetSocketImpl.handleDataReceived(NetSocketImpl.java:321)
	at io.vertx.core.net.impl.NetClientImpl$1.handleMsgReceived(NetClientImpl.java:197)
	at io.vertx.core.net.impl.VertxNetHandler.lambda$channelRead$0(VertxNetHandler.java:64)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:335)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:193)
	at io.vertx.core.net.impl.VertxNetHandler.channelRead(VertxNetHandler.java:64)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:122)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1228)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1039)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
14:04:24.434 [vert.x-eventloop-thread-3] DEBUG o.e.h.c.ConnectionFactoryImpl - connection to container [Hono-Auth-0.0.0.0:5671] at [amqps://hono-service-auth.hono:5671] open
14:04:24.435 [vert.x-eventloop-thread-3] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.IllegalStateException: Result is already complete: failed
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:107)
	at org.eclipse.hono.service.auth.delegating.DelegatingAuthenticationService.lambda$null$0(DelegatingAuthenticationService.java:87)
	at org.eclipse.hono.connection.ConnectionFactoryImpl.lambda$handleConnectionAttemptResult$1(ConnectionFactoryImpl.java:149)
	at io.vertx.proton.impl.ProtonConnectionImpl.fireRemoteOpen(ProtonConnectionImpl.java:357)
	at io.vertx.proton.impl.ProtonTransport.handleSocketBuffer(ProtonTransport.java:105)
	at io.vertx.core.net.impl.NetSocketImpl.handleDataReceived(NetSocketImpl.java:321)
	at io.vertx.core.net.impl.NetClientImpl$1.handleMsgReceived(NetClientImpl.java:197)
	at io.vertx.core.net.impl.VertxNetHandler.lambda$channelRead$0(VertxNetHandler.java:64)
[...]
```
There is no previous log output from the `DelegatingAuthenticationService` and `ConnectionFactoryImpl` classes (the above output is from just after the application start).

**Comment by calohmn** [comment] 2017-10-06 15:12
Maybe the AMQP connection `openHandler` having been invoked twice? But that wouldn't be consistent with the log output (missing "can't open connection..."/"can't connect" log output from `handleConnectionAttemptResult()`).

**Comment by sophokles73** [comment] 2017-10-08 10:20
This happens when the readinness check takes more than 2 seconds to execute. By default, health checks are timed out after 2 secs. So, when the check is finally finished, the `Future` for reporting the result has already failed (due to the timeout).
I will change the readiness check in the `DelegatingAuthenticationService` to only *try* to complete (or fail) the future. So that the stack trace does no longer show up in the log.
However, the real problem here is that the readiness check takes longer than 2 secs (which it shouldn't). I had this problem on my laptop once as well (using minikube). In my case the problem was that DNS look ups  from within the containers took very long because of a wrong resolver configuration on my laptop.

**Comment by sophokles73** [comment] 2017-10-09 07:17
I have made the changes mentioned above. There is not much more I can do from Hono's perspective, so I am closing this issue.
Please open a new one if you stll feel that the problem is caused by Hono and not your DNS resolver configuration.

**Closed by sophokles73** 2017-10-09 07:17 UTC
Labels: enhancement
