### ISSUE TITLE
HonoConnectionImpl throws NPE

### ISSUE THREAD

**Issue by ctron** [eclipse/hono#1286] opened 2019-06-13 11:52 UTC
I just noticed this in the log:

~~~
11:49:18.669 [vert.x-eventloop-thread-0] DEBUG o.e.h.s.http.DefaultFailureHandler - unexpected internal failure
java.lang.NullPointerException: null
~~~

<details>
<summary>Full stack trace</summary>

~~~
11:49:18.669 [vert.x-eventloop-thread-0] DEBUG o.e.h.s.http.DefaultFailureHandler - unexpected internal failure
java.lang.NullPointerException: null
	at org.eclipse.hono.client.impl.HonoConnectionImpl.lambda$createReceiver$19(HonoConnectionImpl.java:685)
	at org.eclipse.hono.util.HonoProtonHelper.executeOrRunOnContext(HonoProtonHelper.java:183)
	at org.eclipse.hono.client.impl.HonoConnectionImpl.executeOrRunOnContext(HonoConnectionImpl.java:226)
	at org.eclipse.hono.client.impl.HonoConnectionImpl.createReceiver(HonoConnectionImpl.java:684)
	at org.eclipse.hono.client.impl.HonoConnectionImpl.createReceiver(HonoConnectionImpl.java:666)
	at org.eclipse.hono.client.impl.AbstractRequestResponseClient.createReceiver(AbstractRequestResponseClient.java:369)
	at org.eclipse.hono.client.impl.AbstractRequestResponseClient.createLinks(AbstractRequestResponseClient.java:351)
	at org.eclipse.hono.client.impl.CredentialsClientImpl.create(CredentialsClientImpl.java:158)
	at org.eclipse.hono.client.impl.CredentialsClientFactoryImpl.lambda$getOrCreateCredentialsClient$1(CredentialsClientFactoryImpl.java:69)
	at org.eclipse.hono.client.impl.CachingClientFactory.getOrCreateClient(CachingClientFactory.java:173)
	at org.eclipse.hono.client.impl.CachingClientFactory.getOrCreateClient(CachingClientFactory.java:146)
	at org.eclipse.hono.client.impl.CredentialsClientFactoryImpl.lambda$getOrCreateCredentialsClient$2(CredentialsClientFactoryImpl.java:67)
	at org.eclipse.hono.util.HonoProtonHelper.executeOrRunOnContext(HonoProtonHelper.java:183)
	at org.eclipse.hono.client.impl.HonoConnectionImpl.executeOrRunOnContext(HonoConnectionImpl.java:226)
	at org.eclipse.hono.client.impl.CredentialsClientFactoryImpl.getOrCreateCredentialsClient(CredentialsClientFactoryImpl.java:66)
	at org.eclipse.hono.service.auth.device.CredentialsApiAuthProvider.getCredentialsClient(CredentialsApiAuthProvider.java:80)
	at org.eclipse.hono.service.auth.device.CredentialsApiAuthProvider.getCredentialsForDevice(CredentialsApiAuthProvider.java:100)
	at org.eclipse.hono.service.auth.device.CredentialsApiAuthProvider.authenticate(CredentialsApiAuthProvider.java:122)
	at org.eclipse.hono.service.auth.device.CredentialsApiAuthProvider.authenticate(CredentialsApiAuthProvider.java:222)
	at io.vertx.ext.web.handler.impl.AuthHandlerImpl.lambda$handle$2(AuthHandlerImpl.java:150)
	at io.vertx.ext.web.handler.impl.ChainAuthHandlerImpl.lambda$iterate$0(ChainAuthHandlerImpl.java:94)
	at org.eclipse.hono.service.http.HonoBasicAuthHandler.lambda$parseCredentials$0(HonoBasicAuthHandler.java:92)
	at io.vertx.ext.web.handler.impl.BasicAuthHandlerImpl.lambda$parseCredentials$0(BasicAuthHandlerImpl.java:80)
	at io.vertx.ext.web.handler.impl.AuthorizationAuthHandler.parseAuthorization(AuthorizationAuthHandler.java:97)
	at io.vertx.ext.web.handler.impl.BasicAuthHandlerImpl.parseCredentials(BasicAuthHandlerImpl.java:53)
	at org.eclipse.hono.service.http.HonoBasicAuthHandler.parseCredentials(HonoBasicAuthHandler.java:85)
	at io.vertx.ext.web.handler.impl.ChainAuthHandlerImpl.iterate(ChainAuthHandlerImpl.java:72)
	at io.vertx.ext.web.handler.impl.ChainAuthHandlerImpl.parseCredentials(ChainAuthHandlerImpl.java:58)
	at io.vertx.ext.web.handler.impl.AuthHandlerImpl.handle(AuthHandlerImpl.java:129)
	at io.vertx.ext.web.handler.impl.AuthHandlerImpl.handle(AuthHandlerImpl.java:39)
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:227)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:121)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:134)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.doEnd(BodyHandlerImpl.java:296)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.end(BodyHandlerImpl.java:276)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl.lambda$handle$0(BodyHandlerImpl.java:87)
	at io.vertx.core.http.impl.HttpServerRequestImpl.doEnd(HttpServerRequestImpl.java:537)
	at io.vertx.core.http.impl.HttpServerRequestImpl.handleEnd(HttpServerRequestImpl.java:526)
	at io.vertx.core.http.impl.Http1xServerConnection.handleEnd(Http1xServerConnection.java:167)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:136)
	at io.vertx.core.net.impl.ConnectionBase.handleRead(ConnectionBase.java:390)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:188)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:174)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1429)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1199)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1243)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
~~~

</details>

**Comment by ctron** [comment] 2019-06-13 11:54
It also looks like as if following requests fail with `already creating client for key`

**Comment by sophokles73** [comment] 2019-06-13 12:24
Is there a way to reproduce this?

**Comment by ctron** [comment] 2019-06-13 12:30
I haven't found one. But I didn't really try.

What I was doing was to quickly send telemetry requests during the startup of the protocol adapter.

**Comment by calohmn** [comment] 2019-06-14 08:36
We also just encountered this issue. It looks like it could have something to do with a previous connection error:
````
Caused by: io.netty.resolver.dns.DnsNameResolverTimeoutException: [/10.96.0.10:53] query timed out after 500 milliseconds (no stack trace available)
2019-06-14 08:18:59.218 [vert.x-eventloop-thread-1] DEBUG o.e.h.c.impl.ConnectionFactoryImpl - can't connect to AMQP 1.0 container [amqps://messaging-default.hono:5671]: Search domain query failed. Original hostname: 'messaging-default.hono' failed to resolve 'messaging-default.hono.hono.svc.cluster.local' after 2 queries
2019-06-14 08:18:59.218 [vert.x-eventloop-thread-1] DEBUG o.e.h.client.impl.HonoConnectionImpl - connection attempt failed
io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'messaging-default.hono' failed to resolve 'messaging-default.hono.hono.svc.cluster.local' after 2 queries
        at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:845)
````
Comparing the current code with the one from 0.9 (HonoClientImpl), one difference is that now there is no `checkConnected()` invocation preceding the receiver creation anymore.

**Comment by sophokles73** [comment] 2019-06-14 10:08
@calohmn that might indeed be the problem. At least this would explain the behavior wrt the context that the problem occurred in for @ctron. Looks like the downstream connection(s) were not established yet when the devices started to send telemetry ...

**Comment by calohmn** [comment] 2019-06-14 13:16
Reproducible with the Lora protocol adapter: It tries to open command consumer links on startup. This is currently done in `AbstractVertxBasedHttpProtocolAdapter.onStartupSuccess`. But in that method, the `commandConsumerFactory` connection might not have been connected yet (see `AbstractProtocolAdapterBase.startInternal`).

**Comment by calohmn** [comment] 2019-06-18 10:59
I've added a `checkConnected()` invocation in `HonoConnection` when creating a sender/receiver. I've also fixed the LoraAdapter to create the consumers only after the connection has been made.
That should fix the NPE.

As a further improvement we could think about introducing some kind of retry mechanism here so that temporary disconnects lead to fewer errors.

**Comment by sophokles73** [comment] 2019-06-18 14:12
@calohmn @ctron can this be closed?

**Comment by ctron** [comment] 2019-06-19 07:52
As I didn't use the lora adapter, is that still fixed with the other adapters as well?

**Comment by calohmn** [comment] 2019-06-19 08:25
Yes, the extra `checkConnected()` check in `HonoConnectionImpl` prevents the NPE.

**Comment by calohmn** [comment] 2019-06-19 08:30
Therefore closing this.

**Closed by calohmn** 2019-06-19 08:30 UTC
Labels: Client, bug

**Comment by calohmn** [comment] 2019-06-20 06:34
As an afterthought here:
We also saw this NPE causing all following receiver creation requests on the given address to fail with `already creating client for key` (in `CachingClientFactory#getOrCreateClient()`.

Since this `getOrCreateClient()` method is used in quite many places and since bugs like the above NPE could be hard to spot with all the `already creating client for key` messages cluttering the logs, I suggest we add exception handling here, see PR #1305.
