### ISSUE TITLE
Support TTL for Telemetry

### ISSUE THREAD

**Issue by b-abel** [eclipse/hono#2702] opened 2021-06-02 13:46 UTC
The [Telemetry API for Kafka](https://www.eclipse.org/hono/docs/api/telemetry-kafka/#produce-telemetry-data) defines a TTL record header to limit the _time-to-live_ of a message. The protocol adapters (at least HTTP and MQTT) already support that devices set a TTL for event messages. For Kafka-based messaging this should be supported for Telemetry messages as well because they are persisted.

**Comment by b-abel** [comment] 2021-09-09 17:11
FMPOV it would be a good first step to set the TTL header for each telemetry message at the protocol adapters. This allows Hono admins to configure the time period after which telemetry messages should be ignored. 
The alternative would be to completely rely on _retention time_, but that is much more heavyweight. Kafka does not delete individual records, but always a whole _log segment_. A newer record in a _log segment_ can therefore prevent the deletion of much older ones. The [interval of the Log Cleaner](https://kafka.apache.org/documentation/#brokerconfigs_log.retention.check.interval.ms) comes on top.
You might also want to configure a larger _retention time_, for example, to analyze the messages at times with lower throughput.

Setting a TTL by default on the protocol adapter would allow to let telemetry messages with QoS 0 expire earlier than those with QoS 1.
In a second step, we can allow devices to set the desired TTL per message, just like for _events_.

**Comment by sophokles73** [comment] 2021-09-10 11:56
Just to get it right: the TTL header information is intended to be read and acted upon by the consumer of the message, i.e. a downstream application, right? There are no technical means (apart from the kafka broker's retention policy) that prevent applications from processing messages having an expired TTL, or am I mistaken?

**Comment by b-abel** [comment] 2021-09-10 15:04
> Just to get it right: the TTL header information is intended to be read and acted upon by the consumer of the message, i.e. a downstream application, right? 

Right. The TTL header is defined by Hono's APIs and is not a mechanism by Kafka. 

> There are no technical means (apart from the kafka broker's retention policy) that prevent applications from processing messages having an expired TTL, or am I mistaken?

I am not aware of any other means. From Kafka's POV the consumer decides what records to read and how to handle (or ignore) them.

**Comment by b-abel** [comment] 2021-09-21 09:59
My proposal is:

1. it should be possible to define a _maximum_ TTL for telemetry messages at the tenant, which will always be set if there is not a lower individual value specified at the message. This is analogous to events where a `max-ttl` can be defined in the limits of the tenant.
2. it should be possible to set separate limits for telemetry messages with QoS 0 and for those with QoS 1. This allows skipping messages with QoS 0 after a short outage or temporary _lag_ of the consumers. Concretely, this means adding the properties `max-ttl-telemetry-qos0` and `max-ttl-telemetry-qos1` to the [resource limits of the tenant](https://www.eclipse.org/hono/docs/api/tenant/#resource-limits-configuration-format).

**Comment by sophokles73** [comment] 2021-09-21 14:06
When using AMQP based messaging infrastructure we let downstream applications decide if they want/need to process a telemetry message. Applications will usually assume that not too much time has passed between the device originally creating the message and the application receiving the message. If in doubt, an application can always take a look at the message's creation time and then either consider it relevant or outdated. Couldn't we use the same approach here? I find it hard to determine a reasonable TTL value for telemetry messages and I guess a device firmware developer will also have a hard time doing that ...

**Comment by sophokles73** [comment] 2021-09-22 06:59
> If you operate Hono with Kafka you (at least implicitly) decide a time-to-live by configuring the retention time of the telemetry topics. But that way it is hard to reason about timing because the retention time is not evaluated per message as I wrote above.

I understand that but I also believe that we are not talking about the Kafka imposed retention time here, do we? The retention time will be set to a value that ideally should make sure that a (running) downstream consumer has a chance to process the (telemetry) message. FMPOV the retention time should also account for hiccups at the downstream consumer, i.e. include a reasonable buffer allowing a consumer to restart when it crashes. However, it doesn't need to account for longer down times of downstream consumers, e.g. because the are running during day time only.

Based on that, I still do not see why we need a TTL on telemetry messages in addition to the message's creation time and the upper limit that is set by the retention time (which will be rather shorter than longer anyway). Can you provide a compelling example of where this seems desirable?

**Comment by b-abel** [comment] 2021-09-22 08:03
> Based on that, I still do not see why we need a TTL on telemetry messages in addition to the message's creation time and the upper limit that is set by the retention time (which will be rather shorter than longer anyway). Can you provide a compelling example of where this seems desirable?

Here is the scenario I had in mind:

 - You operate an instance of Hono as a managed service for customers and a backend service
 - You set a retention time of 60 seconds on telemetry topics so that you don't need too much storage 
 - Your customers now _expect_ that no telemetry message older than 60 seconds will be processed by the backend service
 - What your customers will eventually see: messages will be processed that are e.g. 6 minutes old
 - Result: the "upper limit" is not the upper limit but rather the lower limit of a flexible time frame in which messages may be lost. 

I ran the following experiment to verify the behavior I outlined above:

1. Configured a topic with a retention time of 60 seconds
2. started a producer that produced a couple of hundred messages
3. stopped the producer
4. regularly started a consumer that always consumed from the beginning of the topic

What I saw, as a result, was that for several minutes all messages were returned. Then after about 4-6 minutes all were gone at the same time.

This is IMHO not easy to reason about

**Comment by sophokles73** [comment] 2021-09-22 08:21
I still do not see, why setting a TTL on the telemetry messages would improve the situation here. The consumer still needs to inspect the message's creation time and reason about whether it wants to process the message or discard it. FMPOV including the (generic) TTL value in the message might provide a false level of certainty as to when the message could safely be discarded by consumers.

**Comment by sophokles73** [comment] 2021-09-22 09:02
Any other opinions? @calohmn @kaniyan @dejanb @ctron

**Comment by calohmn** [comment] 2021-09-22 13:20
I also see no clear benefit in adding a TTL header. As a northbound application developer, I would just look at the received record creation time and decide based on that whether to ignore the message.

> Result: the "upper limit" is not the upper limit but rather the lower limit of a flexible time frame in which messages may be lost.

As long as this fact is communicated, I see no problem here.

**Comment by calohmn** [comment] 2021-11-19 15:52
> As a northbound application developer, I would just look at the received record creation time and decide based on that whether to ignore the message.

But, if the northbound application handles messages for many tenants with different TTL requirements (e.g. when it serves as a gateway in front of the real backend application), it would indeed be helpful if the application can drop expired messages early on based on a tenant or message specific TTL.

**Comment by sophokles73** [comment] 2021-11-22 07:21
@calohmn I can see how Eclipse Ditto could take advantage of this mechanism which it already uses for events as well, right?

**Comment by calohmn** [comment] 2021-11-22 08:48
@sophokles73 Yes. That was also the motivation behind #2963, which is a duplicate of this issue, as @b-abel already pointed out.

**Comment by sophokles73** [comment] 2021-11-23 07:58
It looks like we will have the same issue with the command response messages sent via Kafka. So I propose to also allow configuring a *max-ttl-command-response* property in the tenant's resource limits ...

**Closed** 2021-12-15 15:20 UTC
