### ISSUE TITLE
HTTP protocol adapter returns 401 unauthorized when there are networking issues while getting credentials

### ISSUE THREAD

**Issue by DanielMaier-BSI** [eclipse/hono#1158] opened 2019-04-10 10:24 UTC
HTTP protocol adapter returns 401 unauthorized when there are network issues while getting credentials from credentials API. From my point of view it would be more appropriate to return 503 to indicate to the client it is worth to try again.

WDYT?

**Comment by sophokles73** [comment] 2019-04-10 10:36
Absolutely, this seems to be a regression as we already had this behavior fixed in past versions.

**Comment by DanielMaier-BSI** [comment] 2019-04-10 10:38
We are using hono 0.9

**Closed** 2019-04-10 12:41 UTC
Labels: HTTP Adapter, bug
