### ISSUE TITLE
[MQTT/AMQP] Issues with devices not properly disconnecting and then reconnecting

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#2244] opened 2020-10-09 13:34 UTC
When an MQTT device connection gets broken without the MQTT adapter noticing, and when the device then reconnects (before the MQTT keepAlive period has elapsed) and re-subscribes for commands, one of these issues may arise:
- **A:** If reconnect happened on different adapter/verticle instance:
The late disconnect (after the keepAlive period) will trigger a "disconnectedTtdEvent" message, superceding the "connectedTtdEvent" message from the reconnect, meaning the latest such event message doesn't reflect the "connected" state of the device.
- **B:** If reconnect happened on *same* adapter/verticle instance:
The late disconnect will also cause the command consumer from the reconnect attempt to be removed. This means the reconnected device won't receive any commands.

Scenario A described in more detail:
- An MQTT device has subscribed for receiving command messages. 
- The MQTT connection then gets broken somehow, without a proper disconnect getting sent, so that the MQTT adapter first doesn't notice that the device is disconnected.
- Then the MQTT device reconnects with another MQTT adapter instance (or verticle instance) and subscribes again. This means an event message (with `ttd=-1`) is sent downstream, notifying the northbound application about the connected device.
- Then the MQTT adapter, that the device was initially connected with, notices the broken connection via the MQTT keep alive mechanism. This means again an event message is sent downstream, this time meaning the device isn't connected anymore (`ttd=0`). This means the latest event message that the northbound application receives (ie. the "disconnected" event), doesn't reflect the actual connection status of the device. This possibly means that the application doesn't send commands anymore although the device is connected and has subscribed for commands.

When testing with `mosquitto_sub`: The case of the broken (half-open) MQTT connection can be simulated by suspending the `mosquitto_sub` process (CTRL+Z).

Both issues probably also apply to a corresponding AMQP device scenario.

**Comment by calohmn** [comment] 2020-10-12 19:21
Ideas for fixing this:

#### A: If reconnect happened on different adapter/verticle instance
Upon disconnect, when de-registering the command consumer, the command handling adapter instance mapping gets removed.
As there is already a new mapping (from the reconnect/re-subscribe) with a different instance id, this operation will return a 404. In that case the "disconnectedTtdEvent" shall not get sent.

#### B: If reconnect happened on same adapter/verticle instance
When the device reconnects and again subscribes for commands, the existing subscriptions for the device id, *across all MQTT connections*, handled by the verticle, are checked for an already existing subscription with the same device id. If such a subscription is found, it gets disassociated from the (old) connection and the command handler gets removed, causing a "disconnectedTtdEvent" to be sent. The following re-subscribe action will register a new command consumer and send the "connectedTtdEvent". The later disconnect after the keepAlive timeout will have no effect.
This of course means that there can only be one command subscription for the same device at the same time. But that is effectively already the case anyway, since the latest command subscription overwrites a previous one in case of different protocol adapter or verticle instances being involved.

**Comment by sophokles73** [comment] 2020-10-13 11:00
@calohmn this looks like a duplicate of #1483, doesn't it?

**Comment by calohmn** [comment] 2020-10-13 13:35
@sophokles73 It's the same scenario, yes - with the added implications regarding a potentially removed command handler noted here (case B).

**Comment by sophokles73** [comment] 2020-10-13 16:17
can we then close either one in favor of the other?

**Comment by sophokles73** [comment] 2020-10-14 06:14
@calohmn your ideas for addressing this issue sound reasonable to me :+1:

**Comment by sophokles73** [comment] 2020-10-19 14:16
@calohmn can this be closed?

**Closed** 2020-10-22 04:32 UTC
Labels: AMQP Adapter, C&C, MQTT Adapter, bug
