### ISSUE TITLE
Consider supporting hono-ttl also for telemetry topic for Adapters in case of Kafka messaging

### ISSUE THREAD

**Issue by Yannic92** [eclipse/hono#2963] opened 2021-11-19 08:07 UTC
Right now it is not possible to modify the value of `ttl` for Kafka records in the telemetry topic.

AFAIK this is because in AMQP case there was no persistence for telemetry messages and therefore a `ttl` was not required.

For the case of Kafka messaging however this becomes a problem, because even telemetry messages are persisted.
When it comes to an increase of the consumer lag for any reason, it can happen that a telemetry message is consumed with more or less long delay.
Sometimes this could even mean, that the message is not longer valid and therefore should not be processed anymore.

Could you consider to support this header for the telemetry topic as well?

**Comment by b-abel** [comment] 2021-11-20 12:24
Isn't this a duplicate of #2702?

**Comment by sophokles73** [comment] 2021-11-22 09:25
Closed as duplicate of #2702

**Closed by sophokles73** 2021-11-22 09:25 UTC
Labels: duplicate
