### ISSUE TITLE
helm install problem

### ISSUE THREAD

**Issue by alexju88** [eclipse/hono#1106] opened 2019-03-21 14:16 UTC
**I package the eclipse-hono and install it from local repository, but meet following problem:**

[root@cnhwmn01-test local]# helm install --dep-up --debug local/eclipse-hono --name eclipse-hono --namespace hono
[debug] Created tunnel using local port: '39523'

[debug] SERVER: "127.0.0.1:39523"

[debug] Original chart version: ""
[debug] Fetched local/eclipse-hono to /root/.helm/cache/archive/eclipse-hono-0.9.tgz

[debug] CHART PATH: /root/.helm/cache/archive/eclipse-hono-0.9.tgz

Error: release eclipse-hono failed: Secret in version "v1" cannot be handled as a Secret: v1.Secret.ObjectMeta: v1.ObjectMeta.Labels: ReadString: expects " or n, but found 0, error found in #10 byte of ...|version":0.9},"name"|..., bigger context ...|age":"Tiller","release":"eclipse-hono","version":0.9},"name":"hono-artemis-conf","namespace":"hono"}|...

**So I tried another way, install it directly from folder, but meet same problem:**

[root@cnhwmn01-test deploy]# helm install --dep-up --name eclipse-hono --namespace hono eclipse-hono/
Error: release eclipse-hono failed: Secret in version "v1" cannot be handled as a Secret: v1.Secret.ObjectMeta: v1.ObjectMeta.Labels: ReadString: expects " or n, but found 0, error found in #10 byte of ...|version":0.9},"name"|..., bigger context ...|age":"Tiller","release":"eclipse-hono","version":0.9},"name":"hono-artemis-conf","namespace":"hono"}|...

What does this mean?

**Comment by sophokles73** [comment] 2019-03-21 14:19
closing as duplicate of #1105

**Closed by sophokles73** 2019-03-21 14:19 UTC
Labels: duplicate
