### ISSUE TITLE
REST Adapter: Do not return 401 when credentialsClient has no credits yet

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#391] opened 2017-11-02 08:12 UTC
Getting the credits for a newly created CredentialsClient in the REST-Adapter may take a while.
During that time the REST Adapter currently returns a 401 response, wrongly implying that there was something wrong with the credentials. Instead, a 503 (Service unavailable) should be returned.

**Comment by pellmann** [comment] 2017-11-16 13:02
Ticket in vertx-web created: https://github.com/vert-x3/vertx-web/issues/756

**Comment by sophokles73** [comment] 2017-11-16 13:46
@pellmann any idea how to address this issue in the meantime? Or do we want to wait for this being fixed in vert.x 3.5.1?

**Comment by pellmann** [comment] 2017-11-16 14:27
I made a locale fix, where I wrote the cause in the vertx context and used this later - but it is a bad hack und I think the 401 is not such a big problem.. so I think we could wait - WDYT?

**Comment by sophokles73** [comment] 2017-11-16 14:38
well, it requires the client to handle two different errors when in fact there is only ever one ... I would rather implement an *intermediary hack* than requiring clients to treat 401 as 503 ...

**Comment by pellmann** [comment] 2017-11-16 14:47
Okay, I will prepare a PR.

**Comment by sophokles73** [comment] 2017-11-22 08:21
@pellmann do we have a test case for this?

**Comment by pellmann** [comment] 2017-11-23 10:59
We have a unit test where we put an exception with 401 and test for this at the end. There are no systems tests for different situations, at the moment.

**Comment by sophokles73** [comment] 2017-11-23 13:07
fixed in bf1fb52461043c4b008482c8c17fc254db47105d

**Comment by sophokles73** [comment] 2017-11-23 13:08
@calohmn please re-open if you still experience this issue.

**Closed by sophokles73** 2017-11-23 13:08 UTC
Labels: enhancement, REST Adapter
